### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by mrspartak**
Added Dreamer NX printer ID

### CODE REVIEW

**Comment by Mrnt** [comment]
@mrspartak Thanks for that! I just merged it in as a new release if you want to test it.

**Comment by mrspartak** [comment]
Thank you! Now octoprint tries to connect, but I get a new error and can't find any info about it. But I'm still searching

> Changing monitoring state from "Offline" to "Detecting serial port"
Serial port list: ['/dev/bus/usb/001/003']
Connecting to: /dev/bus/usb/001/003
Changing monitoring state from "Detecting serial port" to "Error: Connection error, see Terminal tab"
Unexpected error while connecting to serial port: AUTO SerialException: 'Could not configure port: (25, 'Inappropriate ioctl for device')' @ comm.py:_openSerial:2692 (hook default)

**Comment by mrspartak** [comment]
NVM, I'm connected now. Thanks a lot for your plugin! Maybe one day I will master python and help you maintain it =)

**Comment by Mrnt** [comment]
OK great! I think errors like that may occur if there is a USB connection that is not closed properly, preventing a subsequent connection, but they usually reset fairly quickly.

**Pull request merged**
